Sprint 6 solution
ir0nmand0/java-kanban pull request #1
Opened 2024-02-09 06:45 UTC by ir0nmand0

2024-02-09 06:58 UTC, ir0nmand0 commented
ТЗ6: Реализация метода getHistory должна перекладывать задачи из связного списка в ArrayList для формирования ответа.
"Вариант связного списка, который мы предлагаем реализовать, должен удалять элемент из произвольного места за O(1)"
Использование LinkedHashMap гарантирует, порядок добавления записей (по умолчанию) при итерации первой будет та запись, которая была вставлена в хеш-таблицу самой первой, а последней — самая последняя добавленная запись

2024-02-09 08:20 UTC, EugeneLenkevich requested changes
Привет! Спасибо за PR.

Отличная работа! 
Один небольшой моментик :)

2024-02-09 08:20 UTC, EugeneLenkevich commented on src/manager/InMemoryHistoryManager.java
> -    //За подсказку с O(1) спасибо, а про связанные списки забыл, хотя и писал их когда-то на c++
Связный список мы еще напишет :)

2024-02-09 08:22 UTC, EugeneLenkevich requested changes
.

2024-02-09 08:22 UTC, EugeneLenkevich commented on src/test/HistoryManagerTest.java
> +    private static final List<Task> allHistory = new ArrayList<>();
А давай всю инициализацию перенесем в метод с @BeforeEach, чтобы не было размазано :)

2024-02-12 19:28 UTC, ir0nmand0 commented on src/manager/InMemoryHistoryManager.java
> -    //За подсказку с O(1) спасибо, а про связанные списки забыл, хотя и писал их когда-то на c++
Сделал :)

2024-02-12 19:28 UTC, ir0nmand0 commented on src/test/HistoryManagerTest.java
> +    private static final List<Task> allHistory = new ArrayList<>();
Поправил :)

2024-02-13 03:14 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2024-02-13 04:05 UTC, merged